//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bideas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public Ads()
        {
            this.Users = new HashSet<Users>();
            this.Status1 = new HashSet<Status>();
            this.AdsTypes = new HashSet<AdsType>();
            this.AdsSubcategories = new HashSet<AdsSubcategories>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Location { get; set; }
        public string User { get; set; }
        public string Status { get; set; }
        public string Subcategory { get; set; }
        public int AdsImagesId { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Status> Status1 { get; set; }
        public virtual ICollection<AdsType> AdsTypes { get; set; }
        public virtual ICollection<AdsSubcategories> AdsSubcategories { get; set; }
        public virtual AdsImages AdsImage { get; set; }
    }
}
