//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bideas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdsImages
    {
        public AdsImages()
        {
            this.Ads = new HashSet<Ads>();
            this.Status1 = new HashSet<Status>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string ImgPath { get; set; }
        public int Status { get; set; }
        public string Ad { get; set; }
    
        public virtual ICollection<Ads> Ads { get; set; }
        public virtual ICollection<Status> Status1 { get; set; }
    }
}
