//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bideas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesPermissions
    {
        public RolesPermissions()
        {
            this.Status1 = new HashSet<Status>();
            this.Roles = new HashSet<Roles>();
            this.Permissions = new HashSet<Permissions>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int Role { get; set; }
        public int Permission { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Status> Status1 { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
        public virtual ICollection<Permissions> Permissions { get; set; }
    }
}
