//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bideas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int RolesId { get; set; }
        public int UsersId { get; set; }
        public int UsersRolesId { get; set; }
        public int PermissionsId { get; set; }
        public int RolesPermissionsId { get; set; }
        public int AdsCategoriesId { get; set; }
        public int AdsSubcategoriesId { get; set; }
        public int AdsTypeId { get; set; }
        public int AdsId { get; set; }
        public int AdsImagesId { get; set; }
    
        public virtual Roles Role { get; set; }
        public virtual Users User { get; set; }
        public virtual UsersRoles UsersRole { get; set; }
        public virtual Permissions Permission { get; set; }
        public virtual RolesPermissions RolesPermission { get; set; }
        public virtual AdsCategories AdsCategory { get; set; }
        public virtual AdsSubcategories AdsSubcategory { get; set; }
        public virtual AdsType AdsType { get; set; }
        public virtual Ads Ad { get; set; }
        public virtual AdsImages AdsImage { get; set; }
    }
}
