//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bideas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRoles
    {
        public UsersRoles()
        {
            this.Status1 = new HashSet<Status>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string User { get; set; }
        public string Role { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Status> Status1 { get; set; }
    }
}
